
title: GGameDev
email:
description: >- # this means to ignore newlines until "baseurl:"
  Game dev blog and articles. 
twitter_username: #username
github_username: Ysgrathe
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
#markdown_ext: "markdown, mkdown, mkdn, mkd, md"
remote_theme: mmistakes/minimal-mistakes
# Outputting
#permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Prague

include:
  - _pages
#  - _unreal
#  - _gamedev

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ysgrathe"
  avatar : "/assets/images/captain-squirrel.png"
  bio    : "Everything Game Dev related."
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/jjy2aJ3hj9"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ysgrathe"

footer:
  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Ysgrathe"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

# Collections
#collections_dir: articles

collections:
  unreal:
    output: true
    permalink: /unreal/:path/
  gamedev:
    output: true
    permalink: /gamedev/:path/


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      permalink: /:categories/:title/
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _unreal
  - scope:
      path: ""
      type: unreal
    values:
      layout: single
      class: wide
#      read_time: false
#      author_profile: false
#      share: true
#      comments: true
#      sidebar:
#        nav: "unreal"
  # _gamedev
  - scope:
      path: ""
      type: gamedev
    values:
      layout: single
      class: wide
#      read_time: false
#      author_profile: false
#      share: true
#      comments: true
#      sidebar:
#        nav: "gamedev"     
        
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

